# Generated by Django 3.2.18 on 2023-04-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20230428_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_model_weights',
            name='weights',
        ),
    ]
