# Generated by Django 4.1.8 on 2023-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('model_weights', models.BinaryField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
