# Generated by Django 4.1.8 on 2023-04-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCollection',
        ),
    ]
