# Generated by Django 4.1.8 on 2023-04-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0002_delete_mycollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('model_weights', models.JSONField()),
            ],
        ),
    ]
