# Generated by Django 4.1 on 2023-04-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=50)),
                ('hiredate', models.DateField()),
                ('pointvalue', models.IntegerField()),
                ('managerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app1.employees')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('hrid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hr',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('managerid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'managers',
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('rewardid', models.AutoField(primary_key=True, serialize=False)),
                ('rewardname', models.CharField(max_length=50)),
                ('rewarddescription', models.CharField(blank=True, max_length=255, null=True)),
                ('pointcost', models.IntegerField()),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('pointid', models.AutoField(primary_key=True, serialize=False)),
                ('pointvalue', models.IntegerField()),
                ('dateissued', models.DateField()),
                ('dateredeemed', models.DateField(blank=True, null=True)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.employees')),
                ('rewardid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.rewards')),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='points_sender', to='app1.employees')),
            ],
            options={
                'db_table': 'points',
            },
        ),
    ]
