# Generated by Django 4.1 on 2023-04-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hr',
        ),
        migrations.DeleteModel(
            name='Managers',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='Rewards',
        ),
    ]
