# Generated by Django 4.1 on 2023-04-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
